function report = check_mat_example(source)
%CHECK_MAT_EXAMPLE Check the canonical WP3 MAT test-vector envelope.
%   REPORT = CHECK_MAT_EXAMPLE() checks the repository MAT example.
%   REPORT = CHECK_MAT_EXAMPLE(PATH) checks a MAT file containing the
%   radarTestVector variable. REPORT = CHECK_MAT_EXAMPLE(STRUCT) checks an
%   in-memory radarTestVector struct, which is useful for negative checks.

if nargin == 0
    source = fullfile(fileparts(mfilename("fullpath")), "examples", ...
        "test-vector.mat");
end

examplesDirectory = fullfile(fileparts(mfilename("fullpath")), "examples");
if isstruct(source)
    vector = source;
    sourceDescription = "in-memory radarTestVector";
elseif ischar(source) || (isstring(source) && isscalar(source))
    matPath = char(source);
    requireCondition(isfile(matPath), "source", ...
        "MAT file does not exist: " + string(matPath));
    loaded = load(matPath, "radarTestVector");
    requireCondition(isfield(loaded, "radarTestVector"), "source", ...
        "MAT file must contain the radarTestVector variable");
    vector = loaded.radarTestVector;
    sourceDescription = string(matPath);
else
    requireCondition(false, "source", ...
        "expected a MAT-file path or radarTestVector struct");
end

validateEnvelope(vector, examplesDirectory);

report = struct( ...
    "status", "passed", ...
    "message", "WP3 MAT test-vector example conforms to the checked subset", ...
    "source", sourceDescription, ...
    "configurationSnapshot", fullfile(examplesDirectory, "configuration.json"), ...
    "scenarioSnapshot", fullfile(examplesDirectory, "scenario.json"));

fprintf("PASS: %s (%s)\n", report.message, sourceDescription);
end

function validateEnvelope(vector, examplesDirectory)
requiredFields = { ...
    "schemaName", "schemaVersion", "documentVersion", "id", ...
    "createdUtc", "producer", "configurationId", ...
    "configurationSchemaVersion", "configurationDocumentVersion", ...
    "configurationHash", "scenarioId", "scenarioSchemaVersion", ...
    "scenarioDocumentVersion", "scenarioHash", "configurationSnapshot", ...
    "scenarioSnapshot", "sampleRateHz", "channelCount", "sampleFormat", ...
    "timeEpoch", "fixtureScope", "channelMap", "pulseRecords"};

requireCondition(isstruct(vector) && isscalar(vector), "radarTestVector", ...
    "must be a scalar struct");
for index = 1:numel(requiredFields)
    fieldName = requiredFields{index};
    requireCondition(isfield(vector, fieldName), fieldName, ...
        "required field is missing");
end

textFields = { ...
    "schemaName", "schemaVersion", "documentVersion", "id", ...
    "createdUtc", "producer", "configurationId", ...
    "configurationSchemaVersion", "configurationDocumentVersion", ...
    "configurationHash", "scenarioId", "scenarioSchemaVersion", ...
    "scenarioDocumentVersion", "scenarioHash", "configurationSnapshot", ...
    "scenarioSnapshot", "sampleFormat", "timeEpoch", "fixtureScope"};
for index = 1:numel(textFields)
    validateTextField(vector, textFields{index});
end

requireCondition(strcmp(vector.schemaName, "radar.test-vector"), ...
    "schemaName", "must equal radar.test-vector");
requireCondition(strcmp(vector.schemaVersion, "1.0.0-draft.1"), ...
    "schemaVersion", "must equal 1.0.0-draft.1");
requireCondition(strcmp(vector.documentVersion, "0.1.0"), ...
    "documentVersion", "must equal 0.1.0");
requireCondition(strcmp(vector.configurationId, "g1-revised-candidate"), ...
    "configurationId", "must match the canonical configuration example");
requireCondition(strcmp(vector.scenarioId, "one-receding-target"), ...
    "scenarioId", "must match the canonical scenario example");
requireCondition(strcmp(vector.configurationSchemaVersion, ...
    "1.0.0-draft.1"), "configurationSchemaVersion", ...
    "must match the canonical configuration example");
requireCondition(strcmp(vector.scenarioSchemaVersion, "1.0.0-draft.1"), ...
    "scenarioSchemaVersion", "must match the canonical scenario example");
requireCondition(strcmp(vector.configurationDocumentVersion, "0.1.0"), ...
    "configurationDocumentVersion", "must match the canonical configuration example");
requireCondition(strcmp(vector.scenarioDocumentVersion, "0.1.0"), ...
    "scenarioDocumentVersion", "must match the canonical scenario example");
requireCondition(strcmp(vector.sampleFormat, "real-int16"), "sampleFormat", ...
    "must equal real-int16");
requireCondition(strcmp(vector.fixtureScope, "unit-only"), "fixtureScope", ...
    "canonical example must remain unit-only");

validateScalarValue(vector.sampleRateHz, "sampleRateHz", 150e6, "double");
validateScalarValue(vector.channelCount, "channelCount", 64, "double");
validateHash(vector.configurationHash, "configurationHash", ...
    fullfile(examplesDirectory, "configuration.json"));
validateHash(vector.scenarioHash, "scenarioHash", ...
    fullfile(examplesDirectory, "scenario.json"));

configurationSnapshot = readUtf8File( ...
    fullfile(examplesDirectory, "configuration.json"));
scenarioSnapshot = readUtf8File( ...
    fullfile(examplesDirectory, "scenario.json"));
requireCondition(strcmp(vector.configurationSnapshot, configurationSnapshot), ...
    "configurationSnapshot", ...
    "must equal the exact UTF-8 configuration JSON snapshot");
requireCondition(strcmp(vector.scenarioSnapshot, scenarioSnapshot), ...
    "scenarioSnapshot", ...
    "must equal the exact UTF-8 scenario JSON snapshot");

validateChannelMap(vector.channelMap);
validatePulseRecords(vector.pulseRecords);
end

function validateTextField(vector, fieldName)
value = vector.(fieldName);
requireCondition(ischar(value) && isrow(value) && ~isempty(value), fieldName, ...
    "must be a non-empty character row vector");
end

function validateScalarValue(value, fieldName, expectedValue, expectedClass)
requireCondition(isa(value, expectedClass) && isscalar(value) && ...
    isreal(value) && isfinite(value) && isequal(value, expectedValue), fieldName, ...
    "must be a finite scalar " + string(expectedClass) + " with value " + ...
    string(expectedValue));
end

function validateHash(value, fieldName, sourcePath)
requireCondition(~isempty(regexp(value, "^[0-9a-f]{64}$", "once")), fieldName, ...
    "must be a lowercase 64-character SHA-256 hexadecimal string");
expectedHash = sha256File(sourcePath);
requireCondition(strcmp(value, expectedHash), fieldName, ...
    "does not match the SHA-256 digest of " + string(sourcePath));
end

function validateChannelMap(channelMap)
azimuthIndex = repelem((1:16)', 4, 1);
elevationIndex = repmat((1:4)', 16, 1);
expectedMap = uint8([azimuthIndex, elevationIndex]);
requireCondition(isa(channelMap, "uint8") && isequal(size(channelMap), [64, 2]), ...
    "channelMap", "must be a 64x2 uint8 matrix");
requireCondition(isequal(channelMap, expectedMap), "channelMap", ...
    "must map channels row-major from azimuth 1..16 and elevation 1..4");
end

function validatePulseRecords(records)
recordFields = { ...
    "adcSamples", "adcTick", "pulseStartTick", "pulseSampleCount", ...
    "prfIndex", "prfNominalHz"};
requireCondition(isstruct(records) && isscalar(records), "pulseRecords", ...
    "canonical example must contain one scalar record");
for index = 1:numel(recordFields)
    fieldName = recordFields{index};
    requireCondition(isfield(records, fieldName), "pulseRecords." + string(fieldName), ...
        "required field is missing");
end

samples = records.adcSamples;
requireCondition(isa(samples, "int16") && isequal(size(samples), [32, 64]), ...
    "pulseRecords.adcSamples", "must be a 32x64 int16 matrix");
requireCondition(all(samples(:) == 0), "pulseRecords.adcSamples", ...
    "canonical shape fixture must contain zero-valued samples");

ticks = records.adcTick;
requireCondition(isa(ticks, "uint64") && isequal(size(ticks), [32, 1]), ...
    "pulseRecords.adcTick", "must be a 32x1 uint64 vector");
requireCondition(isequal(ticks, uint64((0:31)')), "pulseRecords.adcTick", ...
    "must contain the monotonic global ticks 0 through 31");

requireCondition(isa(records.pulseStartTick, "uint64") && ...
    isscalar(records.pulseStartTick) && isequal(records.pulseStartTick, uint64(0)), ...
    "pulseRecords.pulseStartTick", "must be the uint64 scalar 0");
requireCondition(isa(records.pulseSampleCount, "uint32") && ...
    isscalar(records.pulseSampleCount) && ...
    isequal(records.pulseSampleCount, uint32(32)), ...
    "pulseRecords.pulseSampleCount", "must be the uint32 scalar 32");
requireCondition(isa(records.prfIndex, "uint8") && isscalar(records.prfIndex) && ...
    isequal(records.prfIndex, uint8(1)), "pulseRecords.prfIndex", ...
    "must be the uint8 scalar 1");
requireCondition(isa(records.prfNominalHz, "double") && ...
    isscalar(records.prfNominalHz) && isfinite(records.prfNominalHz) && ...
    isequal(records.prfNominalHz, 1700), "pulseRecords.prfNominalHz", ...
    "must be the finite double scalar 1700");
end

function text = readUtf8File(filePath)
fileId = fopen(filePath, "r");
requireCondition(fileId >= 0, "snapshot", "cannot open " + string(filePath));
cleanup = onCleanup(@() fclose(fileId));
bytes = fread(fileId, Inf, "*uint8")';
text = native2unicode(bytes, "UTF-8");
clear cleanup
end

function digest = sha256File(filePath)
fileId = fopen(filePath, "r");
requireCondition(fileId >= 0, "hash", "cannot open " + string(filePath));
cleanup = onCleanup(@() fclose(fileId));
bytes = fread(fileId, Inf, "*uint8")';
messageDigest = java.security.MessageDigest.getInstance("SHA-256");
messageDigest.update(bytes);
digestBytes = typecast(messageDigest.digest(), "uint8");
digest = lower(reshape(dec2hex(digestBytes, 2)', 1, []));
clear cleanup
end

function requireCondition(condition, fieldPath, message)
if ~condition
    error("WP3:check_mat_example:Invalid", "%s: %s", ...
        char(fieldPath), char(message));
end
end
