function manifest = buildManifest(options)
%BUILDMANIFEST Build the executable WP4/G2 acceptance matrix.

arguments
    options struct
end

manifest = struct();
manifest.manifestVersion = "1.0.0";
manifest.contractVersion = "1.0.0-draft.2";
manifest.fixtureScope = char(options.FixtureScope);
if options.FixtureScope == "acceptance-evidence"
    manifest.status = "acceptance-evidence";
else
    manifest.status = "temporary-generator-evidence";
end
manifest.generatorVersion = char(options.GeneratorVersion);
manifest.generatorRevision = char(options.GeneratorRevision);
manifest.generatorSeed = options.Seeds.master;
manifest.createdUtc = char(options.CreatedUtc);
manifest.generationParameters = struct("fixtureScope", char(options.FixtureScope));
manifest.seeds = options.Seeds;
manifest.fixtures = [
    makeRow("SCH-001", "schedule.json", "schedule", "testScheduleValid", "accept", "", "", "schedule.recurrence"), ...
    makeRow("SCH-002", "schedule.json", "schedule", "testScheduleTickDiscontinuity", "reject", "TICK_DISCONTINUITY", "records[23].startTick", "schedule.recurrence", replaceMutation("records[23].startTick", 0)), ...
    makeRow("SCH-003", "schedule.json", "schedule", "testScheduleRoleGrammar", "reject", "VALUE_OUT_OF_RANGE", "records[0].role", "schedule.recurrence", replaceMutation("records[0].role", "not-a-role")), ...
    makeRow("SCH-004", "schedule.json", "schedule", "testScheduleVersionMismatch", "reject", "VERSION_MISMATCH", "schemaVersion", "common.version", replaceMutation("schemaVersion", "2.0.0")), ...
    makeRow("SCH-005", "schedule.json", "schedule", "testScheduleDimensionMismatch", "reject", "DIMENSION_MISMATCH", "usableCounts", "schedule.recurrence", replaceMutation("usableCounts", [22, 25, 28, 32])), ...
    makeRow("SCH-006", "schedule.json", "schedule", "testScheduleVersionPrecedence", "reject", "VERSION_MISMATCH", "schemaVersion", "common.version", combinedScheduleMutation()), ...
    makeRow("TIM-001", "timing-gate.mat", "timing", "testTimingDelayAndNearRange", "accept", "", "", "timing.delay-priming"), ...
    makeRow("DDC-001", "ddc-design.mat", "ddc", "testDdcResponse", "accept", "", "", "DDC.passband-ripple"), ...
    makeRow("DDC-002", "ddc-streaming.mat", "ddc-streaming", "testDdcStreamingState", "accept", "", "", "DDC.streaming-state"), ...
    makeRow("DDC-003", "ddc-zero.mat", "ddc-zero", "testDdcZeroInput", "accept", "", "", "DDC.zero-input"), ...
    makeRow("DDC-004", "ddc-ripple-invalid.mat", "ddc", "testDdcRippleDiagnostic", "reject", "DDC_RIPPLE_EXCEEDED", "stage2Numerator", "DDC.passband-ripple"), ...
    makeRow("DDC-005", "ddc-alias-invalid.mat", "ddc", "testDdcAliasDiagnostic", "reject", "DDC_ALIAS_REJECTION", "stage2Numerator", "DDC.alias-rejection"), ...
    makeRow("DDC-006", "ddc-design.mat", "ddc", "testDdcStopbandEdgeDiagnostic", "reject", "DDC_STOPBAND_EDGE", "stopbandStartHz", "DDC.alias-rejection", replaceMutation("stopbandStartHz", 6251000)), ...
    makeRow("DDC-007", "ddc-design.mat", "ddc", "testDdcCoefficientDimension", "reject", "DIMENSION_MISMATCH", "stage2Numerator", "DDC.passband-ripple", replaceMutation("stage2Numerator", 1:10)), ...
    makeRow("DDC-008", "ddc-design.mat", "ddc", "testDdcSemanticPrecedence", "reject", "DDC_STOPBAND_EDGE", "stopbandStartHz", "DDC.alias-rejection", combinedDdcMutation()), ...
    makeRow("DDC-009", "ddc-design.mat", "ddc", "testDdcNonfiniteCoefficient", "reject", "NONFINITE", "stage2Numerator[0]", "DDC.passband-ripple", replaceMutationKind("stage2Numerator[0]", "nan", 0)), ...
    makeRow("DDC-010", "ddc-response-pri.mat", "ddc-response-pri", "testDdcPerPriResponse", "accept", "", "", "DDC.cascade-profile"), ...
    makeRow("DDC-PRI-001", "ddc-pri.mat", "ddc-pri", "testDdcPerPriProcessing", "accept", "", "", "DDC.per-pri"), ...
    makeRow("BEAM-001", "beam-boresight.mat", "beam", "testBeamBoresight", "accept", "", "", "beamforming.shape"), ...
    makeRow("BEAM-002", "beam-positive-30deg.mat", "beam", "testBeamPositiveOffBoresight", "accept", "", "", "beamforming.shape"), ...
    makeRow("BEAM-003", "beam-negative-30deg.mat", "beam", "testBeamNegativeOffBoresight", "accept", "", "", "beamforming.shape"), ...
    makeRow("BEAM-004", "beam-positive-30deg.mat", "beam", "testBeamSignInversion", "reject", "NUMERICAL_MISMATCH", "expectedOutput", "beamforming.shape", replaceMutation("commandAngleDeg", -30)), ...
    makeRow("BEAM-005", "beam-boresight.mat", "beam", "testBeamInputDimension", "reject", "DIMENSION_MISMATCH", "input", "beamforming.shape", replaceMutation("input", zeros(2, 63))), ...
    makeRow("BEAM-006", "beam-zero.mat", "beam", "testBeamZeroInput", "accept", "", "", "beamforming.shape"), ...
    makeRow("BEAM-007", "beam-boresight.mat", "beam", "testBeamVersionPrecedence", "reject", "VERSION_MISMATCH", "schemaVersion", "common.version", replaceMutation("schemaVersion", "2.0.0")), ...
    makeRow("FUS-001", "fusion-cases.json", "fusion-pass", "testFusionPass", "accept", "", "", "fusion.outcome"), ...
    makeRow("FUS-002", "fusion-cases.json", "fusion-fail", "testFusionFail", "accept", "", "", "fusion.outcome"), ...
    makeRow("FUS-003", "fusion-cases.json", "fusion-invalid", "testFusionInvalidOutcome", "accept", "", "", "fusion.outcome"), ...
    makeRow("FUS-004", "fusion-zero.json", "fusion-zero", "testFusionZeroHypotheses", "accept", "", "", "fusion.zero-result"), ...
    makeRow("FUS-005", "fusion-cases.json", "fusion-pass", "testFusionSupportSubset", "reject", "VALUE_OUT_OF_RANGE", "supportMask", "fusion.mask-subset", fusionSupportSubsetMutation()), ...
    makeRow("FUS-006", "fusion-cases.json", "fusion-pass", "testFusionMaskDimension", "reject", "DIMENSION_MISMATCH", "passMask", "fusion.mask-length", replaceMutation("passMask", true)), ...
    makeRow("FUS-007", "fusion-cases.json", "fusion-pass", "testFusionThreshold", "reject", "VALUE_OUT_OF_RANGE", "voteThreshold", "fusion.threshold", replaceMutation("voteThreshold", 2)), ...
    makeRow("FUS-008", "fusion-cases.json", "fusion-pass", "testFusionDiagnosticPrecedence", "reject", "DIMENSION_MISMATCH", "passMask", "fusion.mask-length", combinedFusionMutation()), ...
    makeRow("CLU-001", "clustering-single.json", "clustering", "testClusterSingleAggregate", "accept", "", "", "clustering.components"), ...
    makeRow("CLU-002", "clustering-merge.json", "clustering", "testClusterMergeAggregate", "accept", "", "", "clustering.components"), ...
    makeRow("CLU-003", "clustering-order.json", "clustering", "testClusterInputOrder", "accept", "", "", "clustering.order"), ...
    makeRow("CLU-004", "clustering-no-wrap.json", "clustering", "testClusterNoWrap", "accept", "", "", "clustering.no-wrap"), ...
    makeRow("CLU-005", "clustering-no-bridge.json", "clustering", "testClusterNoBridge", "accept", "", "", "clustering.no-bridge"), ...
    makeRow("CLU-006", "clustering-cross-look.json", "clustering", "testClusterSameLook", "accept", "", "", "clustering.same-look"), ...
    makeRow("CLU-007", "clustering-duplicate-cell.json", "clustering", "testClusterDuplicateCell", "accept", "", "", "clustering.components"), ...
    makeRow("CLU-008", "clustering-zero-empty.json", "clustering", "testClusterZeroResult", "accept", "", "", "clustering.zero-result"), ...
    makeRow("CLU-009", "clustering-zero-ineligible.json", "clustering", "testClusterAllIneligible", "accept", "", "", "clustering.zero-result"), ...
    makeRow("CLU-010", "clustering-tie.json", "clustering", "testClusterStatisticTie", "accept", "", "", "clustering.order"), ...
    makeRow("CLU-011", "clustering-merge.json", "clustering", "testClusterMaskDimension", "reject", "DIMENSION_MISMATCH", "hypotheses[0].validityMask", "clustering.mask-length", replaceMutation("hypotheses[0].validityMask", true(1, 4))), ...
    makeRow("CLU-012", "clustering-merge.json", "clustering", "testClusterAggregateMismatch", "reject", "NUMERICAL_MISMATCH", "clusters[0].rangeM", "clustering.components", replaceMutation("clusters[0].rangeM", 99)), ...
    makeRow("CLU-013", "clustering-merge.json", "clustering", "testClusterUnknownMember", "reject", "VALUE_OUT_OF_RANGE", "clusters[0].hypothesisIds[1]", "clustering.components", replaceMutation("clusters[0].hypothesisIds[1]", "unknown")), ...
    makeRow("CLU-014", "clustering-merge.json", "clustering", "testClusterDiagnosticPrecedence", "reject", "DIMENSION_MISMATCH", "hypotheses[0].validityMask", "clustering.mask-length", combinedClusterMutation()), ...
    makeRow("MIG-001", "", "migration", "testDraft1DirectRejection", "reject", "VERSION_MISMATCH", "schemaVersion", "common.version"), ...
    makeRow("MIG-002", "", "migration", "testDraft1ScheduleAdapter", "accept", "", "", "common.version"), ...
    makeRow("MIG-003", "", "migration", "testDraft1DdcAdapter", "accept", "", "", "DDC.passband-ripple"), ...
    makeRow("MIG-004", "", "migration", "testDraft1FusionAdapter", "accept", "", "", "fusion.outcome"), ...
    makeRow("MIG-005", "", "migration", "testDraft1ClusterAdapter", "accept", "", "", "clustering.components"), ...
    makeRow("MIG-006", "", "migration", "testDraft1MissingLookContext", "reject", "MISSING_FIELD", "context.commandedLooks", "common.version"), ...
    makeRow("MIG-007", "", "migration", "testDraft1AmbiguousLookContext", "reject", "PROVENANCE_MISMATCH", "context.commandedLooks[1]", "common.version"), ...
    makeRow("META-001", "", "meta", "testManifestTraceability", "accept", "", "", "common.version"), ...
    makeRow("META-002", "", "meta", "testGeneratorOracleSeparation", "accept", "", "", "common.version")
];
manifest.testMethodCount = numel(manifest.fixtures);
manifest.artifactProvenance = makeDdcArtifactProvenance(options);
end

function output = makeRow(identifier, artifact, domain, method, expected, code, path, clause, mutation)
if nargin < 9
    mutation = struct([]);
end
output = struct("id", identifier, "artifact", artifact, "domain", domain, ...
    "testMethod", method, "expected", expected, "expectedCode", code, ...
    "expectedPath", path, "clause", "docs/contracts/radar-v1-data-contracts.md#" + clause, ...
    "productionEntryPoint", productionEntryPoint(domain), "provenanceSeed", ...
    seedForDomain(domain), "mutation", mutation);
end

function seed = seedForDomain(domain)
switch domain
    case {"schedule", "timing"}
        seed = 401011;
    case {"ddc", "ddc-streaming", "ddc-zero", "ddc-response-pri", "ddc-pri"}
        seed = 401021;
    case "beam"
        seed = 401031;
    case {"fusion-pass", "fusion-fail", "fusion-invalid", "fusion-zero"}
        seed = 401041;
    case "clustering"
        seed = 401051;
    case "migration"
        seed = 401061;
    otherwise
        seed = 401002;
end
end

function entryPoint = productionEntryPoint(domain)
switch domain
    case "schedule"
        entryPoint = "radardemo.schedule.createReceiveSchedule";
    case "timing"
        entryPoint = "radardemo.timing.evaluateReceiveTiming";
    case "ddc-streaming"
        entryPoint = "radardemo.ddc.processFrame";
    case "ddc-pri"
        entryPoint = "radardemo.ddc.processFrame";
    case "ddc-response-pri"
        entryPoint = "radardemo.ddc.measureResponse";
    case {"ddc", "ddc-zero"}
        entryPoint = "radardemo.ddc.createDesign";
    case "beam"
        entryPoint = "radardemo.beamforming.formCommandedLook";
    case {"fusion-pass", "fusion-fail", "fusion-invalid", "fusion-zero"}
        entryPoint = "radardemo.fusion.fuseFivePrf";
    case "clustering"
        entryPoint = "radardemo.clustering.clusterHypotheses";
    case "migration"
        entryPoint = "adaptWp4Draft1";
    otherwise
        entryPoint = "checkWp4Fixtures";
end
end

function mutation = replaceMutation(path, value)
mutation = struct("operation", "replace", "path", path, "valueKind", "", "value", value);
end

function mutation = replaceMutationKind(path, kind, value)
mutation = struct("operation", "replace", "path", path, "valueKind", kind, "value", value);
end

function mutation = combinedScheduleMutation()
mutation = [replaceMutation("schemaVersion", "2.0.0"), replaceMutation("priSampleCounts[1]", 0)];
end

function mutation = combinedDdcMutation()
mutation = [replaceMutation("stopbandStartHz", 6251000), replaceMutationKind("stage2Numerator", "kaiser", 2)];
end

function mutation = combinedFusionMutation()
mutation = [replaceMutation("passMask", true), replaceMutation("voteThreshold", 2)];
end

function mutation = fusionSupportSubsetMutation()
mutation = [replaceMutation("validityMask", [true, true, true, true, false]), ...
    replaceMutation("supportMask", true(1, 5))];
end

function mutation = combinedClusterMutation()
mutation = [replaceMutation("hypotheses[0].validityMask", true(1, 4)), ...
    replaceMutation("clusters[0].rangeM", 99)];
end

function records = makeDdcArtifactProvenance(options)
records = [makeHistoricalRecord("ddc-design.mat", "legacy-stage2-v1", ...
    "0fe89d45fa20a9f0f68ae6908855dbc61835b083", ...
    "541d89c6f98d4f292a2e8ca4504537440b591cea7348859c44d04276e6ab9a0d"), ...
    makeHistoricalRecord("ddc-streaming.mat", "continuous-state-g2-v1", ...
    "58b3d3a80170d413aa88dd4408490e2056f49379", ...
    "2979d3d0c68c1deacbe097a202b2b3a125b2d7fd6aba19ef842d76bb98d6c616"), ...
    makeHistoricalRecord("ddc-zero.mat", "continuous-state-zero-v1", ...
    "0fe89d45fa20a9f0f68ae6908855dbc61835b083", ...
    "101c7af4cc54b60e87657f627642dd1a26d19e37c9b1f4b4172f7a09e289c04e"), ...
    makeHistoricalRecord("ddc-ripple-invalid.mat", "legacy-stage2-v1", ...
    "0fe89d45fa20a9f0f68ae6908855dbc61835b083", ...
    "fe4c2d5a629666ac2af9e65984e1556c5e3a8fa702e9a4da2c5126d04892bfde"), ...
    makeHistoricalRecord("ddc-alias-invalid.mat", "legacy-stage2-v1", ...
    "0fe89d45fa20a9f0f68ae6908855dbc61835b083", ...
    "e75f61c434d6bca47ce315a32b34e5395e6e272c298d6a8ebaad1a5f13b2956f"), ...
    makeGeneratedRecord("ddc-response-pri.mat", "cascade-peak-v1", options), ...
    makeGeneratedRecord("ddc-pri.mat", "independent-pri-v1", options)];
end

function record = makeHistoricalRecord(artifact, profile, sourceRevision, sha256)
record = struct("artifact", artifact, "profile", profile, ...
    "evidenceScope", "acceptance-evidence", ...
    "generatorVersion", "wp4gen-1.0.0", ...
    "generatorRevision", "0fe89d45fa20a9f0f68ae6908855dbc61835b083", ...
    "createdUtc", "2026-09-24T13:56:08Z", "generatorSeed", 401021, ...
    "sourceRevision", sourceRevision, "sha256", sha256);
end

function record = makeGeneratedRecord(artifact, profile, options)
sourceRevision = string(options.GeneratorRevision);
if isempty(regexp(char(sourceRevision), "^[0-9A-Fa-f]{40}$", "once"))
    sourceRevision = "working-tree";
end
record = struct("artifact", artifact, "profile", profile, ...
    "evidenceScope", char(options.FixtureScope), ...
    "generatorVersion", char(options.GeneratorVersion), ...
    "generatorRevision", char(options.GeneratorRevision), ...
    "createdUtc", char(options.CreatedUtc), "generatorSeed", options.Seeds.ddc, ...
    "sourceRevision", char(sourceRevision), "sha256", "");
end
