function fusion = generateFusionFixtures(options)
%GENERATEFUSIONFIXTURES Record production fusion cases and zero evidence.

arguments
    options struct
end

passCase = makeCase("pass", [true, true, true, false, false], ...
    [true, true, true, false, false], [true, true, true, false, false]);
failCase = makeCase("fail", true(1, 5), true(1, 5), [true, false, false, false, false]);
invalidCase = makeCase("invalid", [true, false, false, false, false], ...
    [true, false, false, false, false], [true, false, false, false, false]);
fusion.cases = struct("schemaName", "radar.wp4.fusion-cases", ...
    "schemaVersion", "1.0.0-draft.2", "seed", options.Seeds.fusion, ...
    "cases", [passCase, failCase, invalidCase]);
fusion.cases = wp4gen.addProvenance(fusion.cases, options, options.Seeds.fusion, "fusion");
fusion.zero = struct("schemaName", "radar.wp4.fusion", ...
    "schemaVersion", "1.0.0-draft.2", "hypotheses", [], "results", [], ...
    "seed", options.Seeds.fusion);
fusion.zero = wp4gen.addProvenance(fusion.zero, options, options.Seeds.fusion, "fusion-zero");
end

function fusionCase = makeCase(caseId, validityMask, supportMask, passMask)
input = struct("validityMask", validityMask, "supportMask", supportMask, ...
    "passMask", passMask, "sourceCellIds", {{ "p1:c1", "p2:c1", "p3:c1" }});
result = radardemo.fusion.fuseFivePrf(input);
fusionCase = struct("caseId", caseId, "validityMask", validityMask, ...
    "supportMask", supportMask, "passMask", passMask, "voteThreshold", 3, ...
    "voteCount", result.voteCount, "outcome", result.outcome, ...
    "sourceCellIds", {{ "p1:c1", "p2:c1", "p3:c1" }});
end
