%% Revised G1 feasibility study for the 150 MS/s narrowband candidate
% This study independently reproduces the revised G1 timing, data-rate,
% ideal DDC identity, and finite-LFM separability evidence. It does not
% validate hardware, noise, SNR, detection probability, or the G2 filters.

clearvars

scriptFolder = fileparts(mfilename("fullpath"));
resultsPath = fullfile(scriptFolder, "radar_v1_revised_g1_results.json");
stage = "initialization";
result = createInitialResult(resultsPath);

try
    stage = "configure revised candidate";
    candidate = createCandidate();
    result.candidate = candidate;

    stage = "calculate data volume";
    result.dataVolume = calculateDataVolume(candidate);

    stage = "evaluate closed-boundary guarded coverage";
    partition = createContinuousPartition(candidate);
    coverage = evaluateCoverage(candidate, partition);
    result.coverage = coverage;

    stage = "evaluate ideal complex mixing and real-only alias";
    result.ddcIdentity = evaluateDdcIdentity(candidate);

    stage = "evaluate finite ideal LFM separability";
    result.finiteLfmSweep = evaluateFiniteLfmSweep(candidate);

    stage = "evaluate acceptance criteria";
    result.acceptance = evaluateAcceptance(result);
    if ~result.acceptance.passed
        error("radar_v1_revised_g1:AcceptanceFailed", ...
            "One or more revised G1 acceptance criteria failed.");
    end

    result.status = "passed";
    result.completedUtc = string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ss'Z'"));
    writeResultJson(resultsPath, result);

    fprintf("Revised G1 passed: coverage %d PRFs, LFM %d/%d, DDC error %.3g.\n", ...
        coverage.minimumCompletePrfCount, ...
        result.finiteLfmSweep.passCount, result.finiteLfmSweep.caseCount, ...
        result.ddcIdentity.maximumComplexMixError);
catch exception
    result.status = "failed";
    result.failure = struct( ...
        "stage", stage, ...
        "identifier", string(exception.identifier), ...
        "message", string(exception.message));
    result.completedUtc = string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ss'Z'"));
    writeResultJson(resultsPath, result);
    rethrow(exception)
end

function result = createInitialResult(resultsPath)
%CREATEINITIALRESULT Create the machine-readable study result skeleton.
result = struct( ...
    "schemaVersion", "radar-v1-revised-g1-v1", ...
    "status", "running", ...
    "studyType", "revised-g1-feasibility", ...
    "scope", "Analytic timing, ideal DDC identity, and ideal finite-LFM separability", ...
    "requirements", ["RAD-V1-023", "RAD-V1-024"], ...
    "decisionRecords", ["ADR 0012", "ADR 0013", "ADR 0015"], ...
    "resultsPath", resultsPath, ...
    "failure", struct("stage", "", "identifier", "", "message", ""), ...
    "limitations", [ ...
        "The front end and image-removal filter are ideal abstractions around 50 MHz.", ...
        "No finite DDC filter, group delay, filter state, or decimator phase is modeled; /4 validation is deferred to G2.", ...
        "No hardware, ENOB, clock jitter, noise, SNR, Pd, Pfa, or real-time claim is made.", ...
        "The 128-return schedule, receive-window priming, and PRF transitions remain G2 work.", ...
        "The two-target result is an ideal matched-filter waveform-stage result only." ...
        ]);
end

function candidate = createCandidate()
%CREATECANDIDATE Define the revised waveform, rate, and timing inputs.
speedOfLightMPerS = 299792458;
wavelengthM = 0.1;
carrierFrequencyHz = speedOfLightMPerS / wavelengthM;
adcSampleRateHz = 150e6;
intermediateRateHz = adcSampleRateHz / 3;
ddcOutputRateHz = intermediateRateHz / 4;
ifCenterHz = 50e6;
bandwidthHz = 10e6;
pulseWidthSeconds = 40e-6;
chirpStartHz = -bandwidthHz / 2;
chirpStopHz = bandwidthHz / 2;
requestedPrfHz = [1700, 1900, 2150, 2450, 2700];
priSampleCounts = [88236, 78948, 69768, 61224, 55560];
priSeconds = priSampleCounts / adcSampleRateHz;
actualPrfHz = 1 ./ priSeconds;
unambiguousRangeM = speedOfLightMPerS * priSeconds / 2;
nativeUnambiguousSpeedMPerS = actualPrfHz * wavelengthM / 4;
adcChannelCount = 16 * 4;
adcWordLengthBits = 16;
blankingTimeSeconds = pulseWidthSeconds;
guardTimeSeconds = 5e-6;
reportedRangeDomainM = [6800, 100000];
internalMaxRangeM = 100050;
numberOfUsableReturns = 128;
numberOfPrimingPri = 1;
radialSpeedMPerS = 800 / 3.6;

% The single global epoch is shared by every channel, PRF, and DDC stage.
dwellDurationSeconds = sum(numberOfUsableReturns * priSeconds);
primingDurationSeconds = sum(numberOfPrimingPri * priSeconds);
transitionGapSeconds = 2 * internalMaxRangeM / speedOfLightMPerS + ...
    blankingTimeSeconds + guardTimeSeconds;
scanDurationSeconds = dwellDurationSeconds + primingDurationSeconds + ...
    (numel(priSampleCounts) - 1) * transitionGapSeconds;
motionHalfRangeM = radialSpeedMPerS * scanDurationSeconds / 2;
nominalBlindHalfWidthM = speedOfLightMPerS * ...
    (blankingTimeSeconds + guardTimeSeconds) / 2;
expandedBlindHalfWidthM = nominalBlindHalfWidthM + motionHalfRangeM;
endpointToleranceM = 32 * eps(max(abs(reportedRangeDomainM)));
wavelengthRelationToleranceM = 1e-15;
wavelengthRelationErrorM = abs(wavelengthM - speedOfLightMPerS / ...
    carrierFrequencyHz);

candidate = struct( ...
    "speedOfLightMPerS", speedOfLightMPerS, ...
    "carrierFrequencyHz", carrierFrequencyHz, ...
    "wavelengthM", wavelengthM, ...
    "wavelengthRelationToleranceM", wavelengthRelationToleranceM, ...
    "wavelengthRelationErrorM", wavelengthRelationErrorM, ...
    "adcSampleRateHz", adcSampleRateHz, ...
    "intermediateRateHz", intermediateRateHz, ...
    "ddcOutputRateHz", ddcOutputRateHz, ...
    "ifCenterHz", ifCenterHz, ...
    "bandwidthHz", bandwidthHz, ...
    "chirpStartHz", chirpStartHz, ...
    "chirpStopHz", chirpStopHz, ...
    "pulseWidthSeconds", pulseWidthSeconds, ...
    "adcChannelCount", adcChannelCount, ...
    "adcWordLengthBits", adcWordLengthBits, ...
    "requestedPrfHz", requestedPrfHz, ...
    "priSampleCounts", priSampleCounts, ...
    "priSeconds", priSeconds, ...
    "actualPrfHz", actualPrfHz, ...
    "unambiguousRangeM", unambiguousRangeM, ...
    "nativeUnambiguousSpeedMPerS", nativeUnambiguousSpeedMPerS, ...
    "minimumNativeUnambiguousSpeedMPerS", min(nativeUnambiguousSpeedMPerS), ...
    "blankingTimeSeconds", blankingTimeSeconds, ...
    "guardTimeSeconds", guardTimeSeconds, ...
    "reportedRangeDomainM", reportedRangeDomainM, ...
    "internalMaxRangeM", internalMaxRangeM, ...
    "numberOfUsableReturns", numberOfUsableReturns, ...
    "numberOfPrimingPri", numberOfPrimingPri, ...
    "radialSpeedMPerS", radialSpeedMPerS, ...
    "dwellDurationSeconds", dwellDurationSeconds, ...
    "primingDurationSeconds", primingDurationSeconds, ...
    "transitionGapSeconds", transitionGapSeconds, ...
    "scanDurationSeconds", scanDurationSeconds, ...
    "motionHalfRangeM", motionHalfRangeM, ...
    "nominalBlindHalfWidthM", nominalBlindHalfWidthM, ...
    "expandedBlindHalfWidthM", expandedBlindHalfWidthM, ...
    "endpointToleranceM", endpointToleranceM, ...
    "sampleEpochPolicy", ...
    "One global t=0 is shared by all channels, PRFs, and DDC stages.", ...
    "scheduleStatus", ...
    "128 usable returns, priming, and transitions are retained as G2 checks.");
end

function dataVolume = calculateDataVolume(candidate)
%CALCULATEDATAVOLUME Calculate raw ADC throughput and bounded capture sizes.
bytesPerSample = candidate.adcWordLengthBits / 8;
rawBytesPerSecond = candidate.adcSampleRateHz * ...
    candidate.adcChannelCount * bytesPerSample;
usableReturnBytes = sum(candidate.priSampleCounts) * ...
    candidate.numberOfUsableReturns * candidate.adcChannelCount * bytesPerSample;
primedCaptureBytes = sum(candidate.priSampleCounts) * ...
    (candidate.numberOfUsableReturns + candidate.numberOfPrimingPri) * ...
    candidate.adcChannelCount * bytesPerSample;
maxPulseSlabBytes = max(candidate.priSampleCounts) * ...
    candidate.adcChannelCount * bytesPerSample;

dataVolume = struct( ...
    "bytesPerSample", bytesPerSample, ...
    "rawBytesPerSecond", rawBytesPerSecond, ...
    "rawDecimalGbPerSecond", rawBytesPerSecond / 1e9, ...
    "usableReturnBytes", usableReturnBytes, ...
    "usableReturnDecimalGb", usableReturnBytes / 1e9, ...
    "primedCaptureBytes", primedCaptureBytes, ...
    "primedCaptureDecimalGb", primedCaptureBytes / 1e9, ...
    "maximumFullPulseSlabBytes", maxPulseSlabBytes, ...
    "maximumFullPulseSlabDecimalMb", maxPulseSlabBytes / 1e6, ...
    "volumeScope", ...
    "64-channel real int16 ADC vectors; no framing or derived-stage storage");
end

function partition = createContinuousPartition(candidate)
%CREATECONTINUOUSPARTITION Find all closed guarded-band endpoints.
lowerRangeM = candidate.reportedRangeDomainM(1);
upperRangeM = candidate.reportedRangeDomainM(2);
numberOfPrfs = numel(candidate.unambiguousRangeM);
endpointCells = cell(1, numberOfPrfs);

for prfIndex = 1:numberOfPrfs
    rangeSpacingM = candidate.unambiguousRangeM(prfIndex);
    firstAliasIndex = max(0, ceil((lowerRangeM - ...
        candidate.expandedBlindHalfWidthM) / rangeSpacingM));
    lastAliasIndex = floor((upperRangeM + ...
        candidate.expandedBlindHalfWidthM) / rangeSpacingM);
    aliasIndices = firstAliasIndex:lastAliasIndex;
    endpointCells{prfIndex} = [ ...
        aliasIndices * rangeSpacingM - candidate.expandedBlindHalfWidthM, ...
        aliasIndices * rangeSpacingM + candidate.expandedBlindHalfWidthM];
end

allEndpointsM = [endpointCells{:}];
boundariesM = unique([lowerRangeM, upperRangeM, ...
    allEndpointsM(allEndpointsM > lowerRangeM & allEndpointsM < upperRangeM)]);
partition = struct( ...
    "boundariesM", boundariesM, ...
    "midpointsM", (boundariesM(1:end - 1) + boundariesM(2:end)) / 2);
end

function coverage = evaluateCoverage(candidate, partition)
%EVALUATECOVERAGE Test every open interval and every closed boundary.
numberOfPrfs = numel(candidate.unambiguousRangeM);
partitionInvalidCounts = zeros(1, numel(partition.midpointsM));
boundaryInvalidCounts = zeros(1, numel(partition.boundariesM));

for partitionIndex = 1:numel(partition.midpointsM)
    [~, partitionInvalidCounts(partitionIndex)] = classifyRange( ...
        partition.midpointsM(partitionIndex), candidate, 0);
end

for boundaryIndex = 1:numel(partition.boundariesM)
    [~, boundaryInvalidCounts(boundaryIndex)] = classifyRange( ...
        partition.boundariesM(boundaryIndex), candidate, ...
        candidate.endpointToleranceM);
end

[maximumOpenInvalid, openIndex] = max(partitionInvalidCounts);
[maximumBoundaryInvalid, boundaryIndex] = max(boundaryInvalidCounts);
worstOpenRangeM = partition.midpointsM(openIndex);
worstBoundaryRangeM = partition.boundariesM(boundaryIndex);
maximumInvalidPrfCount = max(maximumOpenInvalid, maximumBoundaryInvalid);

minimumCompletePrfCount = numberOfPrfs - maximumInvalidPrfCount;
coverage = struct( ...
    "domainM", candidate.reportedRangeDomainM, ...
    "domainKm", candidate.reportedRangeDomainM / 1000, ...
    "guardedBlindHalfWidthM", candidate.expandedBlindHalfWidthM, ...
    "nominalBlindHalfWidthM", candidate.nominalBlindHalfWidthM, ...
    "requiredCompletePrfCount", 3, ...
    "maximumInvalidPrfCount", maximumInvalidPrfCount, ...
    "minimumCompletePrfCount", minimumCompletePrfCount, ...
    "allOpenIntervalsPass", all(partitionInvalidCounts <= numberOfPrfs - 3), ...
    "allClosedBoundariesPass", all(boundaryInvalidCounts <= numberOfPrfs - 3), ...
    "partitionBoundaryCount", numel(partition.boundariesM), ...
    "openIntervalCount", numel(partition.midpointsM), ...
    "worstOpenIntervalMidpointM", worstOpenRangeM, ...
    "worstClosedBoundaryM", worstBoundaryRangeM, ...
    "closedBoundaryPolicy", ...
    "Guarded bands use <= at every partition boundary, including domain endpoints.", ...
    "passed", minimumCompletePrfCount >= 3 && ...
    all(partitionInvalidCounts <= numberOfPrfs - 3) && ...
    all(boundaryInvalidCounts <= numberOfPrfs - 3));
end

function [invalidMask, invalidCount] = classifyRange(rangeM, candidate, toleranceM)
%CLASSIFYRANGE Apply the conservative closed guarded-band definition.
numberOfPrfs = numel(candidate.unambiguousRangeM);
invalidMask = false(1, numberOfPrfs);
thresholdM = candidate.expandedBlindHalfWidthM + toleranceM;

for prfIndex = 1:numberOfPrfs
    rangeSpacingM = candidate.unambiguousRangeM(prfIndex);
    firstAliasIndex = max(0, floor((rangeM - thresholdM) / rangeSpacingM) - 1);
    lastAliasIndex = ceil((rangeM + thresholdM) / rangeSpacingM) + 1;
    aliasIndices = firstAliasIndex:lastAliasIndex;
    invalidMask(prfIndex) = any(abs(rangeM - ...
        aliasIndices * rangeSpacingM) <= thresholdM);
end

invalidCount = sum(invalidMask);
end

function ddcIdentity = evaluateDdcIdentity(candidate)
%EVALUATEDDCIDENTITY Verify ideal image removal, mixing, and /3 decimation.
sampleCount = 1500;
sampleIndices = (0:sampleCount - 1).';
toneFrequenciesHz = [-4, 0, 4] * 1e6;
mixer = exp(-1i * 2 * pi * candidate.ifCenterHz * sampleIndices / ...
    candidate.adcSampleRateHz);
amplitudeErrorTolerance = 1e-10;
phaseErrorToleranceDeg = 1e-8;
sampleErrorTolerance = 1e-10;
toneResults = repmat(struct( ...
    "toneFrequencyHz", 0, ...
    "inputFrequencyHz", 0, ...
    "amplitudeError", 0, ...
    "phaseErrorDeg", 0, ...
    "maximumSampleError", 0, ...
    "passed", false), numel(toneFrequenciesHz), 1);
unfilteredImageProjection = zeros(size(toneFrequenciesHz));
unfilteredDesiredProjection = zeros(size(toneFrequenciesHz));

for toneIndex = 1:numel(toneFrequenciesHz)
    toneFrequencyHz = toneFrequenciesHz(toneIndex);
    inputFrequencyHz = candidate.ifCenterHz + toneFrequencyHz;
    realAdcSignal = cos(2 * pi * inputFrequencyHz * sampleIndices / ...
        candidate.adcSampleRateHz);
    analyticAdcSignal = idealImageRemoval(realAdcSignal);
    mixedSignal = analyticAdcSignal .* mixer;
    mixedDecimated = mixedSignal(1:3:end);
    decimatedIndices = (0:numel(mixedDecimated) - 1).';
    expectedBaseband = exp(1i * 2 * pi * toneFrequencyHz * ...
        decimatedIndices / candidate.intermediateRateHz);
    sampleError = mixedDecimated - expectedBaseband;
    amplitudeError = abs(mean(mixedDecimated .* ...
        conj(expectedBaseband)) - 1);
    phaseErrorDeg = abs(rad2deg(angle(mean(mixedDecimated .* ...
        conj(expectedBaseband)))));

    unfilteredMixed = realAdcSignal .* mixer;
    unfilteredDecimated = unfilteredMixed(1:3:end);
    unfilteredDesiredProjection(toneIndex) = abs(mean( ...
        unfilteredDecimated .* conj(expectedBaseband)));
    unfilteredImageProjection(toneIndex) = abs(mean( ...
        unfilteredDecimated .* expectedBaseband));
    toneResults(toneIndex) = struct( ...
        "toneFrequencyHz", toneFrequencyHz, ...
        "inputFrequencyHz", inputFrequencyHz, ...
        "amplitudeError", amplitudeError, ...
        "phaseErrorDeg", phaseErrorDeg, ...
        "maximumSampleError", max(abs(sampleError)), ...
        "passed", amplitudeError <= amplitudeErrorTolerance && ...
        phaseErrorDeg <= phaseErrorToleranceDeg && ...
        max(abs(sampleError)) <= sampleErrorTolerance);
end

nonzeroToneMask = toneFrequenciesHz ~= 0;
maximumComplexMixError = max([toneResults.maximumSampleError]);
unfilteredFailure = struct( ...
    "toneFrequenciesHz", toneFrequenciesHz(nonzeroToneMask), ...
    "desiredProjectionMagnitude", unfilteredDesiredProjection(nonzeroToneMask), ...
    "imageProjectionMagnitude", unfilteredImageProjection(nonzeroToneMask), ...
    "maximumImageProjectionMagnitude", max(unfilteredImageProjection(nonzeroToneMask)), ...
    "demonstrated", max(unfilteredImageProjection(nonzeroToneMask)) > 0.49, ...
    "conclusion", ...
    "Without ideal image removal, real ADC tones retain an image that aliases into the /3 complex output.");

ddcIdentity = struct( ...
    "inputIsRealAdc", true, ...
    "toneFrequenciesHz", toneFrequenciesHz, ...
    "complexMixDecimationFactor", 3, ...
    "complexOutputRateHz", candidate.intermediateRateHz, ...
    "imageRemovalMethod", ...
    "Ideal analytic-signal image removal: negative DFT bins are zeroed and positive bins doubled.", ...
    "amplitudeErrorTolerance", amplitudeErrorTolerance, ...
    "phaseErrorToleranceDeg", phaseErrorToleranceDeg, ...
    "sampleErrorTolerance", sampleErrorTolerance, ...
    "toneResults", toneResults, ...
    "maximumComplexMixError", maximumComplexMixError, ...
    "complexMixIdentityPassed", all([toneResults.passed]), ...
    "unfilteredFailure", unfilteredFailure, ...
    "unfilteredFailureDemonstrated", unfilteredFailure.demonstrated, ...
    "fourToOneDecimationValidationDeferred", true, ...
    "actualFiniteFiltersDeferredToG2", true, ...
    "conclusion", ...
    "Ideal image removal followed by complex mixing and /3 preserves -4, 0, and +4 MHz baseband tones.");
end

function analyticSignal = idealImageRemoval(realSignal)
%IDEALIMAGEREMOVAL Remove the negative-frequency image in an ideal model.
sampleCount = numel(realSignal);
spectrum = fft(realSignal);
analyticSpectrum = zeros(size(spectrum));
analyticSpectrum(1) = spectrum(1);
analyticSpectrum(2:sampleCount / 2) = ...
    2 * spectrum(2:sampleCount / 2);
analyticSpectrum(sampleCount / 2 + 1) = spectrum(sampleCount / 2 + 1);
analyticSignal = ifft(analyticSpectrum);
end

function sweep = evaluateFiniteLfmSweep(candidate)
%EVALUATEFINITELFMSWEEP Sweep relative phase and native-grid offsets.
relativePhasesDeg = 0:359;
offsetCount = 16;
targetSeparationM = 50;
nativeBandwidthHz = candidate.ddcOutputRateHz;
nativeRangeSpacingM = candidate.speedOfLightMPerS / (2 * nativeBandwidthHz);
outputRangeSpacingM = nativeRangeSpacingM;
caseCount = numel(relativePhasesDeg) * offsetCount;
passCount = 0;
worstValleyDb = -inf;

for phaseDeg = relativePhasesDeg
    relativePhase = exp(1i * pi * phaseDeg / 180);
    for offsetIndex = 0:offsetCount - 1
        offsetM = offsetIndex * nativeRangeSpacingM / offsetCount;
        rangeM = (-2 * nativeRangeSpacingM:outputRangeSpacingM: ...
            targetSeparationM + 2 * nativeRangeSpacingM).' + offsetM;
        response = abs(finiteLfmResponse(rangeM, candidate, 0) + ...
            relativePhase * finiteLfmResponse(rangeM, candidate, ...
            targetSeparationM));
        peakIndices = find(response(2:end - 1) > response(1:end - 2) & ...
            response(2:end - 1) >= response(3:end)) + 1;
        leftIndices = peakIndices( ...
            rangeM(peakIndices) >= -12.5 & rangeM(peakIndices) <= 12.5);
        rightIndices = peakIndices( ...
            rangeM(peakIndices) >= targetSeparationM - 12.5 & ...
            rangeM(peakIndices) <= targetSeparationM + 12.5);

        passed = false;
        if ~isempty(leftIndices) && ~isempty(rightIndices)
            [~, leftBest] = max(response(leftIndices));
            [~, rightBest] = max(response(rightIndices));
            leftPeak = leftIndices(leftBest);
            rightPeak = rightIndices(rightBest);
            if rightPeak > leftPeak + 1
                valleyDb = 20 * log10(min(response(leftPeak:rightPeak)) / ...
                    min(response(leftPeak), response(rightPeak)));
                passed = valleyDb <= -3;
                worstValleyDb = max(worstValleyDb, valleyDb);
            end
        end
        passCount = passCount + passed;
    end
end

sweep = struct( ...
    "idealOnly", true, ...
    "model", ...
    "Finite rectangular-LFM autocorrelation with 40 us support and 10 MHz sweep", ...
    "targetRangesM", [0, targetSeparationM], ...
    "targetSeparationM", targetSeparationM, ...
    "nativeBandwidthHz", nativeBandwidthHz, ...
    "relativePhasesDeg", "0:1:359", ...
    "nativeGridOffsetCount", offsetCount, ...
    "nativeRangeSpacingM", nativeRangeSpacingM, ...
    "outputRangeSpacingM", outputRangeSpacingM, ...
    "peakWindowHalfWidthM", 12.5, ...
    "valleyCriterionDb", -3, ...
    "passCount", passCount, ...
    "caseCount", caseCount, ...
    "worstValleyDb", worstValleyDb, ...
    "passed", passCount == caseCount && worstValleyDb <= -3);
end

function response = finiteLfmResponse(rangeOffsetM, candidate, targetRangeM)
%FINITELFMRESPONSE Return the normalized finite rectangular-LFM response.
delaySeconds = 2 * (rangeOffsetM - targetRangeM) / ...
    candidate.speedOfLightMPerS;
overlapSeconds = max(0, candidate.pulseWidthSeconds - abs(delaySeconds));
chirpRateHzPerSecond = candidate.bandwidthHz / candidate.pulseWidthSeconds;
response = overlapSeconds .* sinc(chirpRateHzPerSecond .* ...
    delaySeconds .* overlapSeconds) .* exp(1i * pi * ...
    chirpRateHzPerSecond .* delaySeconds * candidate.pulseWidthSeconds);
end

function acceptance = evaluateAcceptance(result)
%EVALUATEACCEPTANCE Collect the explicit revised G1 gate outcomes.
acceptance = struct( ...
    "closedBoundaryCoveragePass", result.coverage.passed, ...
    "carrierWavelengthRelationPass", ...
    result.candidate.wavelengthRelationErrorM <= ...
    result.candidate.wavelengthRelationToleranceM, ...
    "nativeDopplerPass", ...
    result.candidate.minimumNativeUnambiguousSpeedMPerS >= 40, ...
    "finiteLfm50mPass", result.finiteLfmSweep.passed, ...
    "complexMixIdentityPass", result.ddcIdentity.complexMixIdentityPassed, ...
    "unfilteredImageFailureDemonstrated", ...
    result.ddcIdentity.unfilteredFailureDemonstrated, ...
    "ratesAndDataVolumeRecorded", ...
    result.dataVolume.rawDecimalGbPerSecond == 19.2, ...
    "g2ScheduleDeferred", true);
acceptance.passed = acceptance.closedBoundaryCoveragePass && ...
    acceptance.carrierWavelengthRelationPass && ...
    acceptance.nativeDopplerPass && acceptance.finiteLfm50mPass && ...
    acceptance.complexMixIdentityPass && ...
    acceptance.unfilteredImageFailureDemonstrated && ...
    acceptance.ratesAndDataVolumeRecorded;
end

function writeResultJson(pathname, result)
%WRITERESULTJSON Write a machine-readable study result.
[fileId, message] = fopen(pathname, "w");
if fileId < 0
    error("radar_v1_revised_g1:ResultWriteFailed", ...
        "Unable to open result path for writing: %s", message);
end
fileCleanup = onCleanup(@() fclose(fileId));
jsonText = jsonencode(result, "PrettyPrint", true);
fwrite(fileId, jsonText, "char");
end
