%% Ideal receive-angle feasibility study for radar V1
% This study uses an isotropic, uncoupled, noiseless 16-by-4 half-wave array.
% It does not establish noisy angle accuracy or operational field of view.

clearvars

speedOfLightMPerS = 299792458;
wavelengthM = 0.1;
carrierFrequencyHz = speedOfLightMPerS/wavelengthM;
elementSpacingM = wavelengthM/2;
waveNumberPerM = 2*pi/wavelengthM;
numberOfAzimuthElements = 16;
numberOfElevationElements = 4;

azimuthHalfPowerDeg = fzero( ...
    @(angleDeg) arrayFactorGain(numberOfAzimuthElements, angleDeg) - 1/sqrt(2), ...
    [0, asind(2/numberOfAzimuthElements)]);
elevationHalfPowerDeg = fzero( ...
    @(angleDeg) arrayFactorGain(numberOfElevationElements, angleDeg) - 1/sqrt(2), ...
    [0, asind(2/numberOfElevationElements)]);
azimuthFirstNullDeg = asind(2/numberOfAzimuthElements);
elevationFirstNullDeg = asind(2/numberOfElevationElements);
verticalTxLossDb = 20*log10(arrayFactorGain( ...
    numberOfElevationElements, [10, 15]));

[positionY, positionZ] = ndgrid( ...
    ((0:numberOfAzimuthElements - 1) - 7.5)*elementSpacingM, ...
    ((0:numberOfElevationElements - 1) - 1.5)*elementSpacingM);
elementY = positionY(:);
elementZ = positionZ(:);

[azimuthGridDeg, elevationGridDeg] = ndgrid(-5:0.1:5, -15:0.1:15);
directionY = cosd(elevationGridDeg(:)).*sind(azimuthGridDeg(:));
directionZ = sind(elevationGridDeg(:));
steeringGrid = exp(1i*waveNumberPerM* ...
    (elementY*directionY.' + elementZ*directionZ.'));

testAnglesDeg = [0, 0; 2, 5; -2, -5; 1.27, 7.36];
angleTests = repmat(struct( ...
    "trueAzimuthDeg", 0, ...
    "trueElevationDeg", 0, ...
    "estimatedAzimuthDeg", 0, ...
    "estimatedElevationDeg", 0, ...
    "azimuthErrorDeg", 0, ...
    "elevationErrorDeg", 0), size(testAnglesDeg, 1), 1);
for testIndex = 1:size(testAnglesDeg, 1)
    trueAzimuthDeg = testAnglesDeg(testIndex, 1);
    trueElevationDeg = testAnglesDeg(testIndex, 2);
    target = exp(1i*waveNumberPerM* ...
        (elementY*cosd(trueElevationDeg)*sind(trueAzimuthDeg) + ...
        elementZ*sind(trueElevationDeg)));
    [~, gridIndex] = max(abs(target'*steeringGrid));
    estimatedAzimuthDeg = azimuthGridDeg(gridIndex);
    estimatedElevationDeg = elevationGridDeg(gridIndex);
    angleTests(testIndex) = struct( ...
        "trueAzimuthDeg", trueAzimuthDeg, ...
        "trueElevationDeg", trueElevationDeg, ...
        "estimatedAzimuthDeg", estimatedAzimuthDeg, ...
        "estimatedElevationDeg", estimatedElevationDeg, ...
        "azimuthErrorDeg", estimatedAzimuthDeg - trueAzimuthDeg, ...
        "elevationErrorDeg", estimatedElevationDeg - trueElevationDeg);
end

maximumAbsErrorDeg = max(abs([ ...
    [angleTests.azimuthErrorDeg], [angleTests.elevationErrorDeg]]));
unitTestToleranceDeg = 0.1;
result = struct( ...
    "schemaVersion", "radar-v1-ideal-angle-feasibility-v1", ...
    "status", "passed", ...
    "scope", "Ideal isotropic uncoupled 16x4 half-wave array; noiseless single target", ...
    "wavelengthM", wavelengthM, ...
    "carrierFrequencyHz", carrierFrequencyHz, ...
    "elementSpacingM", elementSpacingM, ...
    "azimuthElements", numberOfAzimuthElements, ...
    "elevationElements", numberOfElevationElements, ...
    "azimuthHalfPowerWidthDeg", 2*azimuthHalfPowerDeg, ...
    "azimuthFirstNullDeg", azimuthFirstNullDeg, ...
    "elevationHalfPowerWidthDeg", 2*elevationHalfPowerDeg, ...
    "elevationFirstNullDeg", elevationFirstNullDeg, ...
    "boresightTxVerticalAnglesDeg", [10, 15], ...
    "boresightTxVerticalLossDb", verticalTxLossDb, ...
    "searchGridAzimuthDeg", "-5:0.1:5", ...
    "searchGridElevationDeg", "-15:0.1:15", ...
    "angleTests", angleTests, ...
    "maximumAbsoluteTestErrorDeg", maximumAbsErrorDeg, ...
    "proposedNoiselessUnitToleranceDeg", unitTestToleranceDeg, ...
    "limitations", "No noise, calibration error, element pattern, mutual coupling, scan loss, or guaranteed elevation coverage");
if maximumAbsErrorDeg > unitTestToleranceDeg
    result.status = "failed";
end

scriptFolder = fileparts(mfilename("fullpath"));
resultsPath = fullfile(scriptFolder, "radar_v1_angle_feasibility_results.json");
[fileId, message] = fopen(resultsPath, "w");
if fileId < 0
    error("radar_v1_angle:ResultWriteFailed", ...
        "Unable to open result file: %s", message);
end
fileCleanup = onCleanup(@() fclose(fileId));
fwrite(fileId, jsonencode(result, "PrettyPrint", true), "char");
clear fileCleanup

fprintf("Ideal az/el widths: %.3f/%.3f deg; max grid error: %.3f deg.\n", ...
    result.azimuthHalfPowerWidthDeg, result.elevationHalfPowerWidthDeg, ...
    maximumAbsErrorDeg);
if result.status ~= "passed"
    error("radar_v1_angle:UnitToleranceFailed", ...
        "Noiseless angle-grid fixture exceeded the proposed tolerance.");
end

function gain = arrayFactorGain(numberOfElements, angleDeg)
%ARRAYFACTORGAIN Return the normalized half-wave uniform array factor.
elementPositions = ((0:numberOfElements - 1) - (numberOfElements - 1)/2).';
gain = abs(sum(exp(1i*pi*elementPositions*sind(angleDeg)), 1))/numberOfElements;
end
