%% Continuous guarded range coverage study for radar V1
% This study proves continuous coverage of the reported range domain under
% the candidate timing assumptions. It is an analytic timing and echo-window
% study; it does not model noise, detection, Doppler unfolding, or hardware.

clearvars

scriptFolder = fileparts(mfilename("fullpath"));
resultsPath = fullfile(scriptFolder, "radar_v1_coverage_results.json");
stage = "initialization";
result = createInitialResult(resultsPath);

try
    stage = "configure candidate";
    candidate = createCandidate();
    result.candidate = candidate;

    stage = "construct continuous partition";
    partition = createContinuousPartition(candidate);
    result.method = createStudyMethod(candidate, partition);
    result.partition = struct( ...
        "boundaryCount", numel(partition.boundariesM), ...
        "openIntervalCount", numel(partition.midpointsM), ...
        "boundariesM", partition.boundariesM);

    stage = "evaluate open intervals and boundaries";
    evaluation = evaluateCoverage(candidate, partition);
    result.evaluation = evaluation;

    requiredCompletePrfCount = 3;
    result.coverage = struct( ...
        "domainM", candidate.reportedRangeDomainM, ...
        "domainKm", candidate.reportedRangeDomainM / 1000, ...
        "requiredCompletePrfCount", requiredCompletePrfCount, ...
        "maximumInvalidPrfCount", evaluation.maximumInvalidPrfCount, ...
        "minimumCompletePrfCount", evaluation.minimumCompletePrfCount, ...
        "minimumValidPrfCount", evaluation.minimumValidPrfCount, ...
        "allOpenIntervalsPass", evaluation.allOpenIntervalsPass, ...
        "allBoundariesPass", evaluation.allBoundariesPass, ...
        "passed", evaluation.minimumCompletePrfCount >= requiredCompletePrfCount);

    if ~result.coverage.passed
        error("radar_v1_coverage:InsufficientCoverage", ...
            "The reported range domain has fewer than three complete PRFs.");
    end

    result.status = "passed";
    result.completedUtc = string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ss'Z'"));
    writeResultJson(resultsPath, result);

    fprintf("Continuous coverage passed: max invalid PRFs = %d, " + ...
        "min complete PRFs = %d.\n", ...
        evaluation.maximumInvalidPrfCount, evaluation.minimumCompletePrfCount);
catch exception
    result.status = "failed";
    result.failure = struct( ...
        "stage", stage, ...
        "identifier", string(exception.identifier), ...
        "message", string(exception.message));
    result.completedUtc = string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ss'Z'"));
    writeResultJson(resultsPath, result);
    rethrow(exception)
end

function result = createInitialResult(resultsPath)
%CREATEINITIALRESULT Create the machine-readable study result skeleton.
result = struct( ...
    "schemaVersion", "radar-v1-continuous-coverage-v1", ...
    "status", "running", ...
    "studyType", "analytic-continuous-guarded-coverage", ...
    "scope", "Timing and echo-window coverage only; no noisy detection or unfolding", ...
    "resultsPath", resultsPath, ...
    "failure", struct("stage", "", "identifier", "", "message", ""));
end

function candidate = createCandidate()
%CREATECANDIDATE Define the WP2 timing and coverage candidate inputs.
speedOfLightMPerS = 299792458;
samplingRateHz = 625e6;
requestedPrfHz = [1700, 1900, 2150, 2450, 2700];
priSampleCounts = 2 * round(samplingRateHz ./ requestedPrfHz / 2);
priSeconds = priSampleCounts / samplingRateHz;
actualPrfHz = 1 ./ priSeconds;
unambiguousRangeM = speedOfLightMPerS * priSeconds / 2;
blankingTimeSeconds = 40e-6;
guardTimeSeconds = 5e-6;
internalMaxRangeM = 100050;
numberOfPulsesPerPrf = 128;
reportedRangeDomainM = [6800, 100000];
speedMagnitudeMPerS = 800 / 3.6;

dwellDurationSeconds = sum(numberOfPulsesPerPrf * priSeconds);
primingDurationSeconds = sum(priSeconds);
quietGapSeconds = 2 * internalMaxRangeM / speedOfLightMPerS + ...
    blankingTimeSeconds + guardTimeSeconds;
scanDurationSeconds = dwellDurationSeconds + primingDurationSeconds + ...
    (numel(requestedPrfHz) - 1) * quietGapSeconds;
motionHalfRangeM = speedMagnitudeMPerS * scanDurationSeconds / 2;
nominalBlindHalfWidthM = speedOfLightMPerS * ...
    (blankingTimeSeconds + guardTimeSeconds) / 2;
expandedBlindHalfWidthM = nominalBlindHalfWidthM + motionHalfRangeM;
endpointToleranceM = 32 * eps(max(abs(reportedRangeDomainM)));

candidate = struct( ...
    "speedOfLightMPerS", speedOfLightMPerS, ...
    "samplingRateHz", samplingRateHz, ...
    "requestedPrfHz", requestedPrfHz, ...
    "priSampleCounts", priSampleCounts, ...
    "priSeconds", priSeconds, ...
    "actualPrfHz", actualPrfHz, ...
    "unambiguousRangeM", unambiguousRangeM, ...
    "blankingTimeSeconds", blankingTimeSeconds, ...
    "guardTimeSeconds", guardTimeSeconds, ...
    "internalMaxRangeM", internalMaxRangeM, ...
    "numberOfPulsesPerPrf", numberOfPulsesPerPrf, ...
    "reportedRangeDomainM", reportedRangeDomainM, ...
    "speedMagnitudeMPerS", speedMagnitudeMPerS, ...
    "dwellDurationSeconds", dwellDurationSeconds, ...
    "primingDurationSeconds", primingDurationSeconds, ...
    "quietGapSeconds", quietGapSeconds, ...
    "scanDurationSeconds", scanDurationSeconds, ...
    "motionHalfRangeM", motionHalfRangeM, ...
    "nominalBlindHalfWidthM", nominalBlindHalfWidthM, ...
    "expandedBlindHalfWidthM", expandedBlindHalfWidthM, ...
    "endpointToleranceM", endpointToleranceM);
end

function method = createStudyMethod(candidate, partition)
%CREATESTUDYMETHOD Describe the continuous coverage proof and its policy.
method = struct( ...
    "invalidDefinition", ...
    "A PRF is invalid when a closed guarded blind band contains the range.", ...
    "blindBandDefinition", ...
    "For nonnegative integer n, the band is [n*Ru-H, n*Ru+H].", ...
    "expandedHalfWidthDefinition", ...
    "H includes blanking, guard, and half-scan target motion.", ...
    "partitionConstruction", ...
    "Use every band endpoint intersecting the reported domain, plus its endpoints.", ...
    "openIntervalProof", ...
    "The invalid mask is constant on every open partition interval; its midpoint is tested.", ...
    "boundaryPolicy", ...
    "Band endpoints are tested separately with <= and a finite-point tolerance.", ...
    "endpointToleranceM", candidate.endpointToleranceM, ...
    "boundaryCount", numel(partition.boundariesM), ...
    "claim", ...
    "Every range in the reported domain has at least three complete PRFs.");
end

function partition = createContinuousPartition(candidate)
%CREATECONTINUOUSPARTITION Find all analytic blind-band endpoints.
lowerRangeM = candidate.reportedRangeDomainM(1);
upperRangeM = candidate.reportedRangeDomainM(2);
numberOfPrfs = numel(candidate.unambiguousRangeM);
endpointCells = cell(1, numberOfPrfs);

for prfIndex = 1:numberOfPrfs
    rangeSpacingM = candidate.unambiguousRangeM(prfIndex);
    firstAliasIndex = max(0, ceil((lowerRangeM - ...
        candidate.expandedBlindHalfWidthM) / rangeSpacingM));
    lastAliasIndex = floor((upperRangeM + ...
        candidate.expandedBlindHalfWidthM) / rangeSpacingM);
    aliasIndices = firstAliasIndex:lastAliasIndex;
    endpointCells{prfIndex} = [ ...
        aliasIndices * rangeSpacingM - candidate.expandedBlindHalfWidthM, ...
        aliasIndices * rangeSpacingM + candidate.expandedBlindHalfWidthM];
end

allEndpointsM = [endpointCells{:}];
boundariesM = unique([lowerRangeM, upperRangeM, ...
    allEndpointsM(allEndpointsM > lowerRangeM & allEndpointsM < upperRangeM)]);
partition = struct( ...
    "boundariesM", boundariesM, ...
    "midpointsM", (boundariesM(1:end - 1) + boundariesM(2:end)) / 2);
end

function evaluation = evaluateCoverage(candidate, partition)
%EVALUATECOVERAGE Test every open partition and every closed boundary.
numberOfPartitions = numel(partition.midpointsM);
numberOfBoundaries = numel(partition.boundariesM);
partitionTests = repmat(createEmptyRangeTest(), numberOfPartitions, 1);
boundaryTests = repmat(createEmptyRangeTest(), numberOfBoundaries, 1);
partitionInvalidCounts = zeros(1, numberOfPartitions);
boundaryInvalidCounts = zeros(1, numberOfBoundaries);

for partitionIndex = 1:numberOfPartitions
    rangeM = partition.midpointsM(partitionIndex);
    [invalidMask, invalidCount] = classifyRange(rangeM, candidate, 0);
    partitionTests(partitionIndex) = createRangeTest( ...
        partition.boundariesM(partitionIndex), ...
        partition.boundariesM(partitionIndex + 1), rangeM, ...
        invalidMask, invalidCount, numel(candidate.unambiguousRangeM));
    partitionInvalidCounts(partitionIndex) = invalidCount;
end

for boundaryIndex = 1:numberOfBoundaries
    rangeM = partition.boundariesM(boundaryIndex);
    [invalidMask, invalidCount] = classifyRange( ...
        rangeM, candidate, candidate.endpointToleranceM);
    boundaryTests(boundaryIndex) = createRangeTest( ...
        rangeM, rangeM, rangeM, invalidMask, invalidCount, ...
        numel(candidate.unambiguousRangeM));
    boundaryInvalidCounts(boundaryIndex) = invalidCount;
end

allInvalidCounts = [partitionInvalidCounts, boundaryInvalidCounts];
minimumCompletePrfCount = numel(candidate.unambiguousRangeM) - ...
    max(allInvalidCounts);
evaluation = struct( ...
    "partitions", partitionTests, ...
    "boundaries", boundaryTests, ...
    "maximumInvalidPrfCount", max(allInvalidCounts), ...
    "minimumCompletePrfCount", minimumCompletePrfCount, ...
    "minimumValidPrfCount", minimumCompletePrfCount, ...
    "allOpenIntervalsPass", all(partitionInvalidCounts <= ...
    numel(candidate.unambiguousRangeM) - 3), ...
    "allBoundariesPass", all(boundaryInvalidCounts <= ...
    numel(candidate.unambiguousRangeM) - 3));
end

function rangeTest = createEmptyRangeTest()
%CREATEEMPTYRANGETEST Create an empty test record for preallocation.
rangeTest = struct( ...
    "startRangeM", 0, ...
    "endRangeM", 0, ...
    "testedRangeM", 0, ...
    "invalidPrfIndices", zeros(1, 0), ...
    "invalidPrfCount", 0, ...
    "completePrfCount", 0);
end

function rangeTest = createRangeTest(startRangeM, endRangeM, testedRangeM, ...
        invalidMask, invalidCount, numberOfPrfs)
%CREATERANGETEST Create one open-interval or boundary test record.
rangeTest = struct( ...
    "startRangeM", startRangeM, ...
    "endRangeM", endRangeM, ...
    "testedRangeM", testedRangeM, ...
    "invalidPrfIndices", find(invalidMask), ...
    "invalidPrfCount", invalidCount, ...
    "completePrfCount", numberOfPrfs - invalidCount);
end

function [invalidMask, invalidCount] = classifyRange(rangeM, candidate, toleranceM)
%CLASSIFYRANGE Apply the conservative closed-band invalid definition.
numberOfPrfs = numel(candidate.unambiguousRangeM);
invalidMask = false(1, numberOfPrfs);
thresholdM = candidate.expandedBlindHalfWidthM + toleranceM;

for prfIndex = 1:numberOfPrfs
    rangeSpacingM = candidate.unambiguousRangeM(prfIndex);
    firstAliasIndex = max(0, floor((rangeM - thresholdM) / rangeSpacingM) - 1);
    lastAliasIndex = ceil((rangeM + thresholdM) / rangeSpacingM) + 1;
    aliasIndices = firstAliasIndex:lastAliasIndex;
    invalidMask(prfIndex) = any(abs(rangeM - ...
        aliasIndices * rangeSpacingM) <= thresholdM);
end

invalidCount = sum(invalidMask);
end

function writeResultJson(pathname, result)
%WRITERESULTJSON Write a compact machine-readable study result.
[fileId, message] = fopen(pathname, "w");
if fileId < 0
    error("radar_v1_coverage:ResultWriteFailed", ...
        "Unable to open result path for writing: %s", message);
end
fileCleanup = onCleanup(@() fclose(fileId));
jsonText = jsonencode(result, "PrettyPrint", true);
fwrite(fileId, jsonText, "char");
end
