%% Ideal two-target range-resolution study for radar V1
% This finite sweep supports a waveform and output-grid choice. It does not
% test sampled ADC data, DDC, matched filtering, detection, or clustering.

clearvars

speedOfLightMPerS = 299792458;
bandwidthsHz = [200, 250]*1e6;
oversamplingFactors = [1, 4];
relativePhasesDeg = 0:359;
offsetCount = 16;
requiredPassCount = numel(relativePhasesDeg)*offsetCount;

rows = repmat(struct( ...
    "bandwidthHz", 0, ...
    "oversamplingFactor", 0, ...
    "nativeRangeSpacingM", 0, ...
    "outputRangeSpacingM", 0, ...
    "passCount", 0, ...
    "caseCount", 0, ...
    "worstValleyDb", 0), 4, 1);

rowIndex = 0;
for bandwidthHz = bandwidthsHz
    nativeSpacingM = speedOfLightMPerS/(2.5*bandwidthHz);
    for oversamplingFactor = oversamplingFactors
        rowIndex = rowIndex + 1;
        outputSpacingM = nativeSpacingM/oversamplingFactor;
        [passCount, worstValleyDb] = evaluateSweep( ...
            bandwidthHz, outputSpacingM, nativeSpacingM, ...
            relativePhasesDeg, offsetCount, speedOfLightMPerS);
        rows(rowIndex) = struct( ...
            "bandwidthHz", bandwidthHz, ...
            "oversamplingFactor", oversamplingFactor, ...
            "nativeRangeSpacingM", nativeSpacingM, ...
            "outputRangeSpacingM", outputSpacingM, ...
            "passCount", passCount, ...
            "caseCount", requiredPassCount, ...
            "worstValleyDb", worstValleyDb);
    end
end

finePhasesDeg = [-5:0.1:5, 175:0.1:185];
fineNativeSpacingM = speedOfLightMPerS/(2.5*250e6);
[finePassCount, fineWorstValleyDb] = evaluateSweep( ...
    250e6, fineNativeSpacingM/4, fineNativeSpacingM, ...
    finePhasesDeg, offsetCount, speedOfLightMPerS);

carrierFrequencyHz = 3e9;
propagationPhaseDeg = rad2deg(angle(exp( ...
    -1i*4*pi*carrierFrequencyHz/speedOfLightMPerS)));
continuousExamples = repmat(struct( ...
    "bandwidthHz", 0, ...
    "peakRangesM", [0, 0], ...
    "valleyDb", 0), 2, 1);
for bandwidthIndex = 1:numel(bandwidthsHz)
    continuousExamples(bandwidthIndex) = evaluateContinuousExample( ...
        bandwidthsHz(bandwidthIndex), propagationPhaseDeg, ...
        speedOfLightMPerS);
end

expectedPassCounts = [1508, 3440, 4273, 5760];
actualPassCounts = [rows.passCount];
headlineMatchesArchitect = isequal(actualPassCounts, expectedPassCounts) && ...
    (finePassCount == numel(finePhasesDeg)*offsetCount);

result = struct( ...
    "schemaVersion", "radar-v1-ideal-range-resolution-v1", ...
    "status", "passed", ...
    "model", "abs(sinc(2*B*r/c)+exp(1j*phi)*sinc(2*B*(r-1)/c))", ...
    "scope", "Finite ideal coherent point-spread sweep; not sampled DUT acceptance", ...
    "targetRangesM", [0, 1], ...
    "relativePhasesDeg", "0:1:359", ...
    "nativeGridOffsetCount", offsetCount, ...
    "criterion", "Peaks within +/-0.25 m of each target, intervening output sample, valley >=3 dB below weaker peak", ...
    "rows", rows, ...
    "finePhaseSweep", struct( ...
        "phaseSetsDeg", "[-5:0.1:5, 175:0.1:185]", ...
        "bandwidthHz", 250e6, ...
        "oversamplingFactor", 4, ...
        "passCount", finePassCount, ...
        "caseCount", numel(finePhasesDeg)*offsetCount, ...
        "worstValleyDb", fineWorstValleyDb), ...
    "propagationPhaseDeg", propagationPhaseDeg, ...
    "continuousExamples", continuousExamples, ...
    "headlineMatchesArchitect", headlineMatchesArchitect, ...
    "limitations", "Finite ideal sinc sweep omits finite-pulse LFM, ADC, DDC, noise, motion, CFAR, and clustering");

if ~headlineMatchesArchitect
    result.status = "failed";
end

scriptFolder = fileparts(mfilename("fullpath"));
resultsPath = fullfile(scriptFolder, "radar_v1_range_resolution_results.json");
[fileId, message] = fopen(resultsPath, "w");
if fileId < 0
    error("radar_v1_resolution:ResultWriteFailed", ...
        "Unable to open result file: %s", message);
end
fileCleanup = onCleanup(@() fclose(fileId));
fwrite(fileId, jsonencode(result, "PrettyPrint", true), "char");
clear fileCleanup

fprintf("B250 Q4: %d/%d ideal-grid cases; headline match: %d.\n", ...
    rows(4).passCount, rows(4).caseCount, headlineMatchesArchitect);
if ~headlineMatchesArchitect
    error("radar_v1_resolution:UnexpectedCounts", ...
        "Ideal point-spread sweep did not reproduce the architect results.");
end

function [passCount, worstValleyDb] = evaluateSweep( ...
        bandwidthHz, outputSpacingM, nativeSpacingM, phaseValuesDeg, ...
        offsetCount, speedOfLightMPerS)
%EVALUATESWEEP Count finite phase and output-grid-offset split cases.
passCount = 0;
worstValleyDb = -inf;
for phaseDeg = phaseValuesDeg
    for offsetIndex = 0:offsetCount - 1
        offsetM = offsetIndex*nativeSpacingM/offsetCount;
        rangeM = (-2:outputSpacingM:3).' + offsetM;
        response = abs( ...
            sinc(2*bandwidthHz*rangeM/speedOfLightMPerS) + ...
            exp(1i*pi*phaseDeg/180).*sinc( ...
            2*bandwidthHz*(rangeM - 1)/speedOfLightMPerS));
        peakIndices = find( ...
            response(2:end - 1) > response(1:end - 2) & ...
            response(2:end - 1) >= response(3:end)) + 1;
        leftIndices = peakIndices( ...
            rangeM(peakIndices) >= -0.25 & rangeM(peakIndices) <= 0.25);
        rightIndices = peakIndices( ...
            rangeM(peakIndices) >= 0.75 & rangeM(peakIndices) <= 1.25);

        passed = false;
        if ~isempty(leftIndices) && ~isempty(rightIndices)
            [~, leftBest] = max(response(leftIndices));
            [~, rightBest] = max(response(rightIndices));
            leftPeak = leftIndices(leftBest);
            rightPeak = rightIndices(rightBest);
            if rightPeak > leftPeak + 1
                valleyDb = 20*log10( ...
                    min(response(leftPeak:rightPeak))/ ...
                    min(response(leftPeak), response(rightPeak)));
                passed = valleyDb <= -3;
                worstValleyDb = max(worstValleyDb, valleyDb);
            end
        end
        passCount = passCount + passed;
    end
end
end

function example = evaluateContinuousExample( ...
        bandwidthHz, phaseDeg, speedOfLightMPerS)
%EVALUATECONTINUOUSEXAMPLE Measure one fine-grid propagation-phase profile.
rangeM = (-0.5:0.0001:1.5).';
response = abs( ...
    sinc(2*bandwidthHz*rangeM/speedOfLightMPerS) + ...
    exp(1i*pi*phaseDeg/180).*sinc( ...
    2*bandwidthHz*(rangeM - 1)/speedOfLightMPerS));
peakIndices = find( ...
    response(2:end - 1) > response(1:end - 2) & ...
    response(2:end - 1) >= response(3:end)) + 1;
if numel(peakIndices) < 2
    error("radar_v1_resolution:MissingPeaks", ...
        "Continuous ideal profile did not contain two local maxima.");
end
[~, strengthOrder] = sort(response(peakIndices), "descend");
selectedPeakIndices = sort(peakIndices(strengthOrder(1:2)));
valleyDb = 20*log10( ...
    min(response(selectedPeakIndices(1):selectedPeakIndices(2)))/ ...
    min(response(selectedPeakIndices)));
example = struct( ...
    "bandwidthHz", bandwidthHz, ...
    "peakRangesM", rangeM(selectedPeakIndices).', ...
    "valleyDb", valleyDb);
end
